version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15

jobs:
  build-front:
    docker:
      - image: 'circleci/node:erbium'
    steps:
      - checkout
      - run: 
          name: Copy env and build for staging
          command: |
            npm install && cp env-cmdrc .env-cmdrc && CI=false npm run build:staging

  deploy-front-s3:
    docker:
      - image: 'circleci/node:erbium'
    steps:
      - checkout
      - run: 
          name: Copy env and build for production
          command: |
            npm install && cp env-cmdrc .env-cmdrc && CI=false npm run build:production
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: build
          overwrite: true
          to: "s3://ctpanel.pl"


workflows:
  build-and-deploy-staging:
    jobs:
      - deploy-front-s3:
          context: CTPanel
          filters:
            branches:
              only: develop # only deploy on the develop branch