export default {
  logoFont: "'Josefin Sans', sans-serif;",
  mainFont: "'Muli', sans-serif;",
  colorError: '#ff2c2c',
  colorEdit: '#4F86C6',
  colorCancel: '#888888',
  colorWhite: '#fff',
  colorMain: '#009640',
  colorFont: 'rgba(0,0,0,.8)',
  colorBlack: '#000',
  colorHeader: '#152835',
  colorLink: '#9D9EA3',
  modalBackground: 'rgba(0,0,0,.3)',
  borderColor: '#DBDBDB',
  backgroundColor: '#F8F6F7',
  boxShadowColor: 'rgba(0,0,0,.05)',
  checkboxColor: '#EFE5E6',
  tableHeaderColor: '#FCFBFC',
  tableBorderColor: '#F3EEF0',
  logoutButtonColor: '#152835',
};
